name: CD - Terraform

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
      - 'infra/terraform/**'

permissions:
  id-token: write   # required for OIDC
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=terraform init -input=false

      - name: Terraform Plan (create artifact)
        run: |
          terraform -chdir=terraform plan -input=false -out=tfplan.binary
          terraform -chdir=terraform show -no-color tfplan.binary > tfplan.txt

      - name: Upload plan artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: |
            terraform/tfplan.binary
            terraform/tfplan.txt

      - name: Summary (preview)
        run: |
          echo "## Terraform Plan Preview" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`diff" >> $GITHUB_STEP_SUMMARY
          sed -n '1,400p' terraform/tfplan.txt >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

  apply:
    needs: plan
    runs-on: ubuntu-latest
    environment: dev   # <-- requires your approval before this job starts
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}   # from the 'dev' environment
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: terraform

      - name: Terraform Init
        run: terraform -chdir=terraform init -input=false

      - name: Terraform Apply (from approved plan)
        run: terraform -chdir=terraform apply -input=false -auto-approve tfplan.binary
